server:
  port: 8080

spring:
  application:
    name: file-service
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#  transaction:
#    default-timeout: 30  # 事务默认超时时间30秒
#    rollback-on-commit-failure: true
  
  # 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/file_service?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fileservice.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

# Eureka配置
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

file:
  upload:
    path: /data/uploads
    max-size: 104857600  # 100MB
    allowed-types: jpg,jpeg,png,gif,pdf,doc,docx,xls,xlsx,txt,zip,rar

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus  # 暴露prometheus端点
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
        step: 10s  # 采集指标的时间间隔

# 日志配置补充
logging:
  level:
    root: INFO
    com.mini: INFO
  config: classpath:logback-spring.xml
  file:
    path: logs

